<a href="https://colab.research.google.com/github/mihirgupte/pytorch-exercises/blob/main/linear%20regression%20using%20pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
t1 = torch.tensor([[1,2,4,3.],[4.,5,6,3]])
t1.shape

torch.Size([2, 4])

In [3]:
x = torch.tensor(5.,requires_grad=True)
w = torch.tensor(4.)
b = torch.tensor(3.)
print(w)

tensor(4.)


In [4]:
y = w*x+b
y.backward()
print(x.grad,w.grad,b.grad)

tensor(4.) None None


In [5]:
import numpy as np
x  = np.array([1,2,3])
print(x)
torch.from_numpy(x)

[1 2 3]


tensor([1, 2, 3])

In [6]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [7]:
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [8]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs,targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]]) tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [9]:
b=torch.randn(2,requires_grad=True)
w = torch.randn(2,3,requires_grad=True)
print(b,w)
print(w.t())

tensor([0.0470, 0.1657], requires_grad=True) tensor([[ 0.2219, -0.6418, -0.1868],
        [ 0.1969, -0.7191,  0.9043]], requires_grad=True)
tensor([[ 0.2219,  0.1969],
        [-0.6418, -0.7191],
        [-0.1868,  0.9043]], grad_fn=<TBackward>)


In [10]:
def model(x):
  return x @ w.t() + b

In [11]:
preds = model(inputs)
print(preds)

tensor([[-34.7870,   5.2453],
        [-48.1933,  12.6791],
        [-77.4825, -26.6109],
        [-11.8283,  22.7863],
        [-59.3300,   8.0212]], grad_fn=<AddBackward0>)


In [12]:
diff = targets - preds
print(diff*diff)
torch.sum(diff*diff)
torch.numel(diff*diff)

tensor([[ 8242.2803,  4193.1660],
        [16690.9004,  7800.5786],
        [38605.3555, 25475.6309],
        [ 1144.3552,   202.0302],
        [26351.0391, 12316.2852]], grad_fn=<MulBackward0>)


10

In [13]:
def mse(preds):
  diff = targets - preds
  diffs = diff * diff
  return torch.sum(diffs)/torch.numel(diffs)

In [14]:
loss = mse(preds)
print(loss)

tensor(14102.1621, grad_fn=<DivBackward0>)


In [15]:
loss.backward()

In [16]:
print(b.grad)
print(w.grad)

tensor([-122.5242,  -87.5758])
tensor([[-10025.8545, -12163.7363,  -7236.5884],
        [ -7151.5547,  -8952.7617,  -5197.7681]])


In [17]:
with torch.no_grad():
  w -= (w.grad)*1e-5
  b -= (b.grad)*1e-5
  w.grad.zero_()
  b.grad.zero_()

In [18]:
print(w,b)

tensor([[ 0.3222, -0.5202, -0.1144],
        [ 0.2684, -0.6295,  0.9563]], requires_grad=True) tensor([0.0482, 0.1665], requires_grad=True)


In [19]:
preds = model(inputs)
loss = mse(preds)
print(loss)

tensor(9920.1191, grad_fn=<DivBackward0>)


In [31]:
for i in range(100):
  preds = model(inputs)
  loss = mse(preds)
  print(loss)
  loss.backward()
  with torch.no_grad():
    w -= (w.grad)*1e-5
    b -= (b.grad)*1e-5
    w.grad.zero_()
    b.grad.zero_()

tensor(4.1224, grad_fn=<DivBackward0>)
tensor(4.1151, grad_fn=<DivBackward0>)
tensor(4.1079, grad_fn=<DivBackward0>)
tensor(4.1007, grad_fn=<DivBackward0>)
tensor(4.0934, grad_fn=<DivBackward0>)
tensor(4.0863, grad_fn=<DivBackward0>)
tensor(4.0791, grad_fn=<DivBackward0>)
tensor(4.0720, grad_fn=<DivBackward0>)
tensor(4.0648, grad_fn=<DivBackward0>)
tensor(4.0577, grad_fn=<DivBackward0>)
tensor(4.0507, grad_fn=<DivBackward0>)
tensor(4.0436, grad_fn=<DivBackward0>)
tensor(4.0365, grad_fn=<DivBackward0>)
tensor(4.0295, grad_fn=<DivBackward0>)
tensor(4.0225, grad_fn=<DivBackward0>)
tensor(4.0155, grad_fn=<DivBackward0>)
tensor(4.0086, grad_fn=<DivBackward0>)
tensor(4.0016, grad_fn=<DivBackward0>)
tensor(3.9947, grad_fn=<DivBackward0>)
tensor(3.9878, grad_fn=<DivBackward0>)
tensor(3.9809, grad_fn=<DivBackward0>)
tensor(3.9740, grad_fn=<DivBackward0>)
tensor(3.9671, grad_fn=<DivBackward0>)
tensor(3.9603, grad_fn=<DivBackward0>)
tensor(3.9534, grad_fn=<DivBackward0>)
tensor(3.9467, grad_fn=<D

In [32]:
preds = model(inputs)
loss = mse(preds)
print(loss)

tensor(3.4809, grad_fn=<DivBackward0>)


In [33]:
print(preds)
print(targets)

tensor([[ 57.3504,  70.2212],
        [ 81.0675, 101.9401],
        [120.9867, 130.2119],
        [ 21.9859,  36.4814],
        [ 99.4196, 121.6906]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
